name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pr_number}/comments
          owner: ${{ github.event.pull_request.repository.owner.login }}
          repo: ${{ github.event.pull_request.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          body: |
            Pull request: #${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
