name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create GitHub deployment
        id: deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/vzvu3k6k-sandbox/fictional-octo-enigma/deployments
          ref: ${{ github.sha }}
          environment: staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub deployment status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/vzvu3k6k-sandbox/fictional-octo-enigma/deployments/{deployment_id}
          deployment_id: ${{ fromJson(steps.deployment.outputs.data).id }}
          state: success
          target_url: https://example.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}