name: Inactive deployments

on:
  pull_request:
    types: [synchronize]

jobs:
  inactive_deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { data: deployments } = github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
            });
            for (const d of deployments) {
              github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: d.id,
                state: "inactive",
              });
            }